DROP TABLE IF EXISTS student;

CREATE TABLE student (
  id  VARCHAR(255)  PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book (
  id  VARCHAR(255)  PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  student_id  VARCHAR(255),
  CONSTRAINT FK_BOOK_STUDENT FOREIGN KEY (student_id) REFERENCES student(id)
  ON DELETE CASCADE
);
